bot:
  token: "7362667458:AAHAnFrQ2SQKXmi34LU4ucckqGwYyGNruV4"
  host_addr: "0.0.0.0:8502"
  webhook_addr: "https://bf8c-85-159-228-113.ngrok-free.app"

storage:
  host: "localhost"
  port: 5432
  user: ""
  password: ""
  db_name: ""